'use client';

import { useState, useEffect, useCallback } from 'react';

interface LineItem {
  description: string;
  qty: number;
  unitPrice: number;
}

interface Doc {
  id: string;
  type: string;
  number: string;
  customerName: string;
  customerEmail: string | null;
  customerPhone: string | null;
  customerAddress: string | null;
  lineItems: LineItem[];
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  notes: string | null;
  depositPercent: number | null;
  validUntil: string | null;
  dueDate: string | null;
  status: string;
  paidAt: string | null;
  createdAt: string;
  meta?: AutoQuoteMeta | null;
}

/** Set by /api/instant-quote when a visitor generates an estimate on the site. */
interface AutoQuoteMeta {
  autoGenerated?: boolean;
  estimateLow?: number;
  estimateHigh?: number;
  factors?: string[];
  inputs?: {
    serviceName?: string;
    variantLabel?: string;
    quantity?: number;
    cityName?: string;
    difficultAccess?: boolean;
    removalRequired?: boolean;
    outOfHours?: boolean;
  };
}

interface CustomerLite {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  location: string;
}

const WA_NUMBER = '447397066538';
const SITE_URL = 'https://www.sigmashopfronts.com';

const QUOTE_STATUSES = [
  { value: 'sent', label: 'Sent', color: 'bg-blue-100 text-blue-700' },
  { value: 'accepted', label: 'Accepted', color: 'bg-emerald-100 text-emerald-700' },
  { value: 'declined', label: 'Declined', color: 'bg-red-100 text-red-700' },
  { value: 'expired', label: 'Expired', color: 'bg-slate-100 text-slate-500' },
];

const INVOICE_STATUSES = [
  { value: 'sent', label: 'Sent', color: 'bg-blue-100 text-blue-700' },
  { value: 'paid', label: 'Paid', color: 'bg-emerald-100 text-emerald-700' },
  { value: 'overdue', label: 'Overdue', color: 'bg-red-100 text-red-700' },
  { value: 'cancelled', label: 'Cancelled', color: 'bg-slate-100 text-slate-500' },
];

const AUTO_STATUSES = [
  { value: 'auto', label: 'New', color: 'bg-amber-100 text-amber-700' },
  { value: 'contacted', label: 'Contacted', color: 'bg-blue-100 text-blue-700' },
  { value: 'quoted', label: 'Quoted', color: 'bg-emerald-100 text-emerald-700' },
  { value: 'dead', label: 'Not proceeding', color: 'bg-slate-100 text-slate-500' },
];

function statusMeta(type: string, val: string) {
  const list =
    type === 'invoice' ? INVOICE_STATUSES : type === 'auto-quote' ? AUTO_STATUSES : QUOTE_STATUSES;
  return list.find((s) => s.value === val) || { value: val, label: val, color: 'bg-slate-100 text-slate-500' };
}

function emptyForm() {
  return {
    number: '',
    customerId: '',
    customerName: '',
    customerEmail: '',
    customerPhone: '',
    customerAddress: '',
    lineItems: [{ description: '', qty: 1, unitPrice: 0 }] as LineItem[],
    vatEnabled: false,
    vatRate: 20,
    notes: '',
    depositPercent: '',
    issueDate: '',
    validUntil: '',
    dueDate: '',
    projectReference: '',
    scope: '',
    specifications: '',
    leadTime: '',
    photoDrawing: '',
  };
}

export default function DocumentsAdminPage() {
  const [apiKey, setApiKey] = useState('');
  const [authed, setAuthed] = useState(false);
  const [tab, setTab] = useState<'quote' | 'invoice' | 'auto-quote'>('quote');
  const [documents, setDocuments] = useState<Doc[]>([]);
  const [customers, setCustomers] = useState<CustomerLite[]>([]);
  const [loading, setLoading] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm());
  const [error, setError] = useState('');
  const [createdDoc, setCreatedDoc] = useState<Doc | null>(null);
  const [editingDocId, setEditingDocId] = useState<string | null>(null);
  const [urlQuery, setUrlQuery] = useState('');

  useEffect(() => {
    setUrlQuery(window.location.search);
  }, []);

  const makeHeaders = useCallback(() => ({ Authorization: 'Bearer ' + apiKey, 'Content-Type': 'application/json' }), [apiKey]);

  const fetchDocuments = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/admin/documents?type=' + tab, { headers: makeHeaders() });
      if (res.status === 401) { setAuthed(false); return; }
      const data = await res.json();
      setDocuments(data.documents || []);
    } catch {
      setError('Failed to load documents');
    }
    setLoading(false);
  }, [apiKey, tab, makeHeaders]);

  const fetchCustomers = useCallback(async () => {
    try {
      const res = await fetch('/api/admin/customers', { headers: makeHeaders() });
      if (!res.ok) return;
      const data = await res.json();
      setCustomers((data.customers || []).map((c: CustomerLite) => ({ id: c.id, name: c.name, phone: c.phone, email: c.email, location: c.location })));
    } catch {
      // non-critical
    }
  }, [makeHeaders]);

  useEffect(() => {
    const saved = sessionStorage.getItem('admin_key');
    if (saved) { setApiKey(saved); setAuthed(true); }
  }, []);

  useEffect(() => { if (authed) { fetchDocuments(); fetchCustomers(); } }, [authed, tab, fetchDocuments, fetchCustomers]);

  function handleLogin(e: React.FormEvent) {
    e.preventDefault();
    sessionStorage.setItem('admin_key', apiKey);
    setAuthed(true);
  }

  function openCreate() {
    setForm(emptyForm());
    setCreatedDoc(null);
    setEditingDocId(null);
    setError('');
    setShowForm(true);
  }

  function editDoc(doc: Doc) {
    const meta = (doc as unknown as { meta?: { projectReference?: string; scope?: string; specifications?: string; leadTime?: string; photoDrawing?: string } }).meta || {};
    setForm({
      number: doc.number,
      customerId: '',
      customerName: doc.customerName,
      customerEmail: doc.customerEmail || '',
      customerPhone: doc.customerPhone || '',
      customerAddress: doc.customerAddress || '',
      lineItems: doc.lineItems.length > 0 ? doc.lineItems.map(li => ({ ...li })) : [{ description: '', qty: 1, unitPrice: 0 }],
      vatEnabled: doc.vatRate > 0,
      vatRate: doc.vatRate || 20,
      notes: doc.notes || '',
      depositPercent: doc.depositPercent ? String(doc.depositPercent) : '',
      issueDate: (doc as unknown as { issueDate?: string | null }).issueDate ? ((doc as unknown as { issueDate: string }).issueDate).split('T')[0] : doc.createdAt.split('T')[0],
      validUntil: doc.validUntil ? doc.validUntil.split('T')[0] : '',
      dueDate: doc.dueDate ? doc.dueDate.split('T')[0] : '',
      projectReference: meta.projectReference || '',
      scope: meta.scope || '',
      specifications: meta.specifications || '',
      leadTime: meta.leadTime || '',
      photoDrawing: meta.photoDrawing || '',
    });
    setEditingDocId(doc.id);
    setCreatedDoc(null);
    setError('');
    setShowForm(true);
  }

  function pickCustomer(id: string) {
    const c = customers.find((x) => x.id === id);
    if (!c) { setForm({ ...form, customerId: '' }); return; }
    setForm({ ...form, customerId: c.id, customerName: c.name, customerPhone: c.phone, customerEmail: c.email || '', customerAddress: c.location });
  }

  function updateLineItem(idx: number, patch: Partial<LineItem>) {
    const items = [...form.lineItems];
    items[idx] = { ...items[idx], ...patch };
    setForm({ ...form, lineItems: items });
  }

  function addLineItem() {
    setForm({ ...form, lineItems: [...form.lineItems, { description: '', qty: 1, unitPrice: 0 }] });
  }

  function removeLineItem(idx: number) {
    setForm({ ...form, lineItems: form.lineItems.filter((_, i) => i !== idx) });
  }

  const subtotal = form.lineItems.reduce((sum, li) => sum + (Number(li.qty) || 0) * (Number(li.unitPrice) || 0), 0);
  const vatAmount = form.vatEnabled ? subtotal * (form.vatRate / 100) : 0;
  const total = subtotal + vatAmount;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');

    const validItems = form.lineItems.filter((li) => li.description.trim());
    if (!form.customerName.trim() || validItems.length === 0) {
      setError('Customer name and at least one line item description are required.');
      return;
    }

    const payload = {
      type: tab,
      ...(editingDocId && form.number.trim() ? { number: form.number.trim() } : {}),
      customerId: form.customerId || null,
      customerName: form.customerName,
      customerEmail: form.customerEmail || null,
      customerPhone: form.customerPhone || null,
      customerAddress: form.customerAddress || null,
      lineItems: validItems,
      vatRate: form.vatEnabled ? form.vatRate : 0,
      notes: form.notes || null,
      depositPercent: tab === 'invoice' && form.depositPercent ? Number(form.depositPercent) : null,
      issueDate: form.issueDate || null,
      validUntil: tab === 'quote' && form.validUntil ? form.validUntil : null,
      dueDate: tab === 'invoice' && form.dueDate ? form.dueDate : null,
      meta: tab === 'quote'
        ? {
            projectReference: form.projectReference.trim() || undefined,
            scope: form.scope.trim() || undefined,
            specifications: form.specifications.trim() || undefined,
            leadTime: form.leadTime.trim() || undefined,
            photoDrawing: form.photoDrawing || undefined,
          }
        : null,
    };

    try {
      let res: Response;
      if (editingDocId) {
        res = await fetch('/api/admin/documents/' + editingDocId, { method: 'PATCH', headers: makeHeaders(), body: JSON.stringify(payload) });
      } else {
        res = await fetch('/api/admin/documents', { method: 'POST', headers: makeHeaders(), body: JSON.stringify(payload) });
      }
      if (!res.ok) { const d = await res.json(); setError(d.error || 'Save failed'); return; }
      const data = await res.json();
      if (editingDocId) {
        setShowForm(false);
        setEditingDocId(null);
      } else {
        setCreatedDoc(data.document);
      }
      fetchDocuments();
    } catch {
      setError('Network error');
    }
  }

  async function updateStatus(doc: Doc, status: string) {
    await fetch('/api/admin/documents/' + doc.id, { method: 'PATCH', headers: makeHeaders(), body: JSON.stringify({ status }) });
    fetchDocuments();
  }

  async function deleteDoc(id: string) {
    if (!confirm('Delete this document? This cannot be undone.')) return;
    await fetch('/api/admin/documents/' + id, { method: 'DELETE', headers: makeHeaders() });
    fetchDocuments();
  }

  function linkFor(doc: Doc) {
    return SITE_URL + '/' + doc.type + '/' + doc.id;
  }

  function copyLink(doc: Doc) {
    navigator.clipboard.writeText(linkFor(doc));
    alert('Link copied to clipboard');
  }

  function sendWhatsApp(doc: Doc) {
    if (!doc.customerPhone) { alert('No phone number for this customer'); return; }
    const first = doc.customerName.split(' ')[0];
    let msg: string;
    if (doc.type === 'auto-quote') {
      // No public page for auto-estimates — send the figures and offer a survey.
      const lo = (doc.meta?.estimateLow ?? doc.subtotal).toLocaleString();
      const hi = (doc.meta?.estimateHigh ?? doc.total).toLocaleString();
      const what = doc.meta?.inputs?.serviceName || 'your enquiry';
      msg = `Hi ${first}, thanks for using our instant estimate for ${what} (ref ${doc.number}). Your guide price was £${lo} – £${hi}. I'd like to arrange a free site survey so we can confirm an exact fixed price — when suits you? — Sigma Shop Fronts`;
    } else {
      const label = doc.type === 'invoice' ? 'invoice' : 'quote';
      msg = `Hi ${first}, here's your ${label} ${doc.number} from Sigma Shop Fronts:\n${linkFor(doc)}`;
    }
    const phone = doc.customerPhone.replace(/[\s\-()]/g, '').replace(/^0/, '44');
    window.open('https://wa.me/' + phone + '?text=' + encodeURIComponent(msg), '_blank');
  }

  if (!authed) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 p-4">
        <form onSubmit={handleLogin} className="bg-white rounded-2xl shadow-lg p-8 w-full max-w-sm space-y-4">
          <h1 className="text-2xl font-heading font-bold text-slate-800 text-center">Quotes &amp; Invoices</h1>
          <p className="text-sm text-slate-400 text-center">Enter your admin key to continue</p>
          <input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="Admin key"
            className="w-full px-4 py-3 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500 outline-none" />
          <button type="submit" className="w-full py-3 bg-slate-800 text-white font-semibold rounded-lg hover:bg-slate-800/90 transition-colors">
            Sign In
          </button>
        </form>
      </div>
    );
  }

  const statusList =
    tab === 'invoice' ? INVOICE_STATUSES : tab === 'auto-quote' ? AUTO_STATUSES : QUOTE_STATUSES;
  const isAuto = tab === 'auto-quote';

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-30">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-heading font-bold text-slate-800">Quotes &amp; Invoices</h1>
            <p className="text-xs text-slate-400">Create shareable quotes and invoices for customers</p>
          </div>
          <a href={'/admin' + urlQuery} className="text-sm text-slate-500 hover:text-slate-800">&larr; Job Tracker</a>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-6 space-y-6">
        {error && (
          <div className="bg-red-50 text-red-700 px-4 py-3 rounded-lg text-sm flex justify-between items-center">
            {error}
            <button onClick={() => setError('')} className="text-red-400 hover:text-red-600 text-lg font-bold ml-4">&times;</button>
          </div>
        )}

        <div className="flex items-center justify-between">
          <div className="inline-flex bg-white rounded-lg border border-slate-200 p-1">
            <button onClick={() => setTab('quote')}
              className={'px-4 py-2 text-sm font-semibold rounded-md transition-colors ' + (tab === 'quote' ? 'bg-slate-800 text-white' : 'text-slate-500 hover:text-slate-800')}>
              Quotes
            </button>
            <button onClick={() => setTab('invoice')}
              className={'px-4 py-2 text-sm font-semibold rounded-md transition-colors ' + (tab === 'invoice' ? 'bg-slate-800 text-white' : 'text-slate-500 hover:text-slate-800')}>
              Invoices
            </button>
            <button onClick={() => setTab('auto-quote')}
              className={'px-4 py-2 text-sm font-semibold rounded-md transition-colors ' + (isAuto ? 'bg-slate-800 text-white' : 'text-slate-500 hover:text-slate-800')}>
              Auto-Gen
            </button>
          </div>
          {!isAuto && (
          <button onClick={openCreate}
            className="flex items-center gap-2 px-4 py-2.5 bg-slate-800 text-white text-sm font-semibold rounded-lg hover:bg-slate-800/90 transition-colors">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M12 5v14M5 12h14" /></svg>
            New {tab === 'quote' ? 'Quote' : 'Invoice'}
          </button>
          )}
        </div>

        <div className="bg-white rounded-2xl border border-slate-200/60 overflow-hidden">
          {loading ? (
            <div className="py-20 text-center text-slate-400">Loading...</div>
          ) : documents.length === 0 ? (
            <div className="py-20 text-center">
              <p className="text-slate-400 text-sm">
                No {isAuto ? 'auto-generated estimates' : tab === 'quote' ? 'quotes' : 'invoices'} yet
              </p>
              {isAuto ? (
                <p className="mt-2 text-xs text-slate-400">
                  These appear automatically when a visitor uses the instant estimate tool.
                </p>
              ) : (
                <button onClick={openCreate} className="mt-3 text-sm text-blue-600 font-semibold hover:underline">Create the first one</button>
              )}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="bg-slate-50/80 border-b border-slate-100">
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Number</th>
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Customer</th>
                    {isAuto && (
                      <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Requirements</th>
                    )}
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                      {isAuto ? 'Estimate Shown' : 'Total'}
                    </th>
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Status</th>
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Created</th>
                    <th className="py-3 px-4 text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {documents.map((doc) => {
                    const st = statusMeta(doc.type, doc.status);
                    return (
                      <tr key={doc.id} className="border-b border-slate-100/60 hover:bg-slate-50/50 transition-colors">
                        <td className="py-3 px-4 text-sm font-semibold text-slate-800">{doc.number}</td>
                        <td className="py-3 px-4">
                          <p className="text-sm text-slate-700">{doc.customerName}</p>
                          <p className="text-xs text-slate-400">{doc.customerPhone}</p>
                          {isAuto && doc.customerEmail && (
                            <p className="text-xs text-slate-400">{doc.customerEmail}</p>
                          )}
                        </td>
                        {isAuto && (
                          <td className="py-3 px-4 max-w-xs">
                            <p className="text-sm text-slate-700">
                              {doc.meta?.inputs?.serviceName || '—'}
                              {doc.meta?.inputs?.quantity && doc.meta.inputs.quantity > 1
                                ? ` × ${doc.meta.inputs.quantity}`
                                : ''}
                            </p>
                            <p className="text-xs text-slate-400">{doc.meta?.inputs?.variantLabel}</p>
                            {doc.meta?.inputs?.cityName && (
                              <p className="text-xs text-slate-400">{doc.meta.inputs.cityName}</p>
                            )}
                            {(doc.meta?.factors?.length ?? 0) > 0 && (
                              <p className="text-xs text-amber-600 mt-0.5">
                                {doc.meta!.factors!.join(' · ')}
                              </p>
                            )}
                            {doc.notes && (
                              <p className="text-xs text-slate-500 mt-1 italic">“{doc.notes}”</p>
                            )}
                          </td>
                        )}
                        <td className="py-3 px-4 text-sm text-slate-700 whitespace-nowrap">
                          {isAuto
                            ? `£${(doc.meta?.estimateLow ?? doc.subtotal).toLocaleString()} – £${(doc.meta?.estimateHigh ?? doc.total).toLocaleString()}`
                            : `£${doc.total.toLocaleString()}`}
                        </td>
                        <td className="py-3 px-4">
                          <select value={doc.status} onChange={(e) => updateStatus(doc, e.target.value)}
                            className={'text-xs font-semibold rounded-full px-2.5 py-1 border-0 outline-none cursor-pointer ' + st.color}>
                            {statusList.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}
                          </select>
                        </td>
                        <td className="py-3 px-4 text-xs text-slate-400">{new Date(doc.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}</td>
                        <td className="py-3 px-4">
                          <div className="flex items-center gap-1">
                            {!isAuto && (
                            <>
                            <a href={linkFor(doc).replace(SITE_URL, '')} target="_blank" title="View"
                              className="p-1.5 rounded hover:bg-slate-100 text-slate-400 hover:text-slate-800 transition-colors">
                              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" /><circle cx="12" cy="12" r="3" /></svg>
                            </a>
                            <button onClick={() => editDoc(doc)} title="Edit"
                              className="p-1.5 rounded hover:bg-slate-100 text-slate-400 hover:text-slate-800 transition-colors">
                              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" /><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" /></svg>
                            </button>
                            <button onClick={() => copyLink(doc)} title="Copy link"
                              className="p-1.5 rounded hover:bg-slate-100 text-slate-400 hover:text-slate-800 transition-colors">
                              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></svg>
                            </button>
                            </>
                            )}
                            {doc.customerPhone && (
                              <button onClick={() => sendWhatsApp(doc)} title="Send via WhatsApp"
                                className="p-1.5 rounded hover:bg-green-50 text-slate-400 hover:text-green-600 transition-colors">
                                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>
                              </button>
                            )}
                            <button onClick={() => deleteDoc(doc.id)} title="Delete"
                              className="p-1.5 rounded hover:bg-red-50 text-slate-400 hover:text-red-500 transition-colors">
                              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" /></svg>
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>

      {showForm && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-start justify-center pt-[6vh] px-4 overflow-y-auto">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl p-6 mb-10">
            {createdDoc ? (
              <div className="space-y-4">
                <div className="w-14 h-14 bg-green-100 rounded-full flex items-center justify-center mx-auto">
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M20 6L9 17l-5-5" stroke="#16a34a" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
                </div>
                <h2 className="text-lg font-heading font-bold text-slate-800 text-center">{createdDoc.number} created</h2>
                <div className="bg-slate-50 rounded-lg p-3 text-sm text-slate-700 break-all text-center">{linkFor(createdDoc)}</div>
                <div className="flex gap-2">
                  <button onClick={() => copyLink(createdDoc)} className="flex-1 py-2.5 border border-slate-200 text-slate-800 text-sm font-semibold rounded-lg hover:bg-slate-50">Copy Link</button>
                  {createdDoc.customerPhone && (
                    <button onClick={() => sendWhatsApp(createdDoc)} className="flex-1 py-2.5 bg-[#25D366] text-white text-sm font-semibold rounded-lg hover:bg-[#20ba5a]">Send WhatsApp</button>
                  )}
                </div>
                <button onClick={() => setShowForm(false)} className="w-full py-2.5 bg-slate-800 text-white text-sm font-semibold rounded-lg hover:bg-slate-800/90">Done</button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-heading font-bold text-slate-800">{editingDocId ? 'Edit' : 'New'} {tab === 'quote' ? 'Quote' : 'Invoice'}</h2>
                  <button type="button" onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-800 text-xl">&times;</button>
                </div>

                {editingDocId && (
                  <div>
                    <label className="block text-xs font-medium text-slate-500 mb-1">{tab === 'quote' ? 'Quote' : 'Invoice'} Number</label>
                    <input value={form.number} onChange={(e) => setForm({ ...form, number: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                )}

                {customers.length > 0 && (
                  <div>
                    <label className="block text-xs font-medium text-slate-500 mb-1">Link to existing customer <span className="text-slate-300">(optional)</span></label>
                    <select value={form.customerId} onChange={(e) => pickCustomer(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm bg-white focus:ring-2 focus:ring-blue-500/40 outline-none">
                      <option value="">— Manual entry —</option>
                      {customers.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}
                    </select>
                  </div>
                )}

                <div className="grid grid-cols-2 gap-3">
                  <div className="col-span-2 sm:col-span-1">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Customer Name *</label>
                    <input required value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                  <div className="col-span-2 sm:col-span-1">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Phone</label>
                    <input value={form.customerPhone} onChange={(e) => setForm({ ...form, customerPhone: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                  <div className="col-span-2 sm:col-span-1">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Email</label>
                    <input type="email" value={form.customerEmail} onChange={(e) => setForm({ ...form, customerEmail: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                  <div className="col-span-2 sm:col-span-1">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Address / Location</label>
                    <input value={form.customerAddress} onChange={(e) => setForm({ ...form, customerAddress: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                </div>

                {tab === 'quote' && (
                  <>
                    <div>
                      <label className="block text-xs font-medium text-slate-500 mb-1">Project Reference <span className="text-slate-300">(e.g. Aluminium Shopfront)</span></label>
                      <input value={form.projectReference} onChange={(e) => setForm({ ...form, projectReference: e.target.value })}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-500 mb-1">Scope of Work <span className="text-slate-300">(one bullet per line)</span></label>
                      <textarea rows={3} value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })}
                        placeholder={'Straight aluminium shopfront double door with fixed glass panels either side.\nAluminium shopfront single door with fixed return & front glass panels either side.'}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none resize-none" />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-500 mb-1">Specifications <span className="text-slate-300">(lines ending with &quot;:&quot; become headings, other lines become bullets)</span></label>
                      <textarea rows={6} value={form.specifications} onChange={(e) => setForm({ ...form, specifications: e.target.value })}
                        placeholder={'Glazing:\nDoor: Double glazed with 4mm toughened glass on both sides.\nFrame & Materials:\nAluminium frame: 100mm x 45mm box section, commercial-grade.'}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none resize-none" />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-500 mb-1">Photo / Drawing <span className="text-slate-300">(optional — shown on the quote)</span></label>
                      {form.photoDrawing ? (
                        <div className="relative inline-block">
                          {/* eslint-disable-next-line @next/next/no-img-element */}
                          <img src={form.photoDrawing} alt="Attached" className="max-h-40 rounded-lg border border-slate-200" />
                          <button type="button" onClick={() => setForm({ ...form, photoDrawing: '' })}
                            className="absolute -top-2 -right-2 w-6 h-6 bg-red-500 text-white rounded-full text-xs flex items-center justify-center hover:bg-red-600">
                            &times;
                          </button>
                        </div>
                      ) : (
                        <input type="file" accept="image/*"
                          onChange={(e) => {
                            const file = e.target.files?.[0];
                            if (!file) return;
                            if (file.size > 2 * 1024 * 1024) { setError('Image must be under 2MB'); return; }
                            const reader = new FileReader();
                            reader.onload = () => setForm((prev) => ({ ...prev, photoDrawing: reader.result as string }));
                            reader.readAsDataURL(file);
                          }}
                          className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none file:mr-3 file:py-1 file:px-3 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200" />
                      )}
                    </div>
                  </>
                )}

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <label className="block text-xs font-medium text-slate-500">{tab === 'quote' ? 'Price Options * (shown as red "PRICE FOR ..." lines)' : 'Line Items *'}</label>
                    <button type="button" onClick={addLineItem} className="text-xs text-blue-600 font-semibold hover:underline">+ Add {tab === 'quote' ? 'option' : 'item'}</button>
                  </div>
                  <div className="space-y-2">
                    {form.lineItems.map((li, idx) => (
                      <div key={idx} className="flex gap-2 items-start">
                        <input placeholder={tab === 'quote' ? 'e.g. Straight Shopfront' : 'Description'} value={li.description} onChange={(e) => updateLineItem(idx, { description: e.target.value })}
                          className="flex-1 px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                        {tab === 'invoice' && (
                          <input type="number" min="0" step="1" placeholder="Qty" value={li.qty} onChange={(e) => updateLineItem(idx, { qty: Number(e.target.value) })}
                            className="w-16 px-2 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                        )}
                        <div className="relative w-28">
                          <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 text-sm">£</span>
                          <input type="number" min="0" step="0.01" placeholder="Price" value={li.unitPrice} onChange={(e) => updateLineItem(idx, { unitPrice: Number(e.target.value) })}
                            className="w-full pl-6 pr-2 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                        </div>
                        <button type="button" onClick={() => removeLineItem(idx)} disabled={form.lineItems.length === 1}
                          className="p-2 text-slate-400 hover:text-red-500 disabled:opacity-30">
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" /></svg>
                        </button>
                      </div>
                    ))}
                  </div>
                </div>

                {tab === 'quote' && (
                  <div>
                    <label className="block text-xs font-medium text-slate-500 mb-1">Lead Time <span className="text-slate-300">(e.g. 2 weeks from confirmation)</span></label>
                    <input value={form.leadTime} onChange={(e) => setForm({ ...form, leadTime: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                )}

                <div className="flex items-center justify-between bg-slate-50 rounded-lg p-3">
                  <label className="flex items-center gap-2 text-sm text-slate-700">
                    <input type="checkbox" checked={form.vatEnabled} onChange={(e) => setForm({ ...form, vatEnabled: e.target.checked })} />
                    {tab === 'quote' ? 'Include VAT (20%)' : 'Add VAT'}
                  </label>
                  {form.vatEnabled && tab === 'invoice' && (
                    <div className="flex items-center gap-1">
                      <input type="number" min="0" max="100" step="0.5" value={form.vatRate} onChange={(e) => setForm({ ...form, vatRate: Number(e.target.value) })}
                        className="w-16 px-2 py-1 border border-slate-200 rounded text-sm text-right" />
                      <span className="text-sm text-slate-500">%</span>
                    </div>
                  )}
                </div>

                {tab === 'invoice' && (
                  <div className="text-right space-y-1 text-sm">
                    <p className="text-slate-500">Subtotal: <span className="text-slate-700 font-medium">£{subtotal.toFixed(2)}</span></p>
                    {form.vatEnabled && <p className="text-slate-500">VAT ({form.vatRate}%): <span className="text-slate-700 font-medium">£{vatAmount.toFixed(2)}</span></p>}
                    <p className="text-slate-800 font-heading font-bold text-lg">Total: £{total.toFixed(2)}</p>
                  </div>
                )}

                <div className="grid grid-cols-2 gap-3">
                  <div className="col-span-2 sm:col-span-1">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Date <span className="text-slate-300">(issue date on document)</span></label>
                    <input type="date" value={form.issueDate} onChange={(e) => setForm({ ...form, issueDate: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                  </div>
                  {tab === 'quote' ? (
                    <div className="col-span-2 sm:col-span-1">
                      <label className="block text-xs font-medium text-slate-500 mb-1">Valid Until</label>
                      <input type="date" value={form.validUntil} onChange={(e) => setForm({ ...form, validUntil: e.target.value })}
                        className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                    </div>
                  ) : (
                    <>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-xs font-medium text-slate-500 mb-1">Due Date</label>
                        <input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
                          className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                      </div>
                      <div className="col-span-2 sm:col-span-1">
                        <label className="block text-xs font-medium text-slate-500 mb-1">Deposit Required <span className="text-slate-300">(% of total, optional)</span></label>
                        <input type="number" min="0" max="100" step="5" placeholder="e.g. 40" value={form.depositPercent}
                          onChange={(e) => setForm({ ...form, depositPercent: e.target.value })}
                          className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none" />
                      </div>
                    </>
                  )}
                  <div className="col-span-2">
                    <label className="block text-xs font-medium text-slate-500 mb-1">Notes <span className="text-slate-300">(payment details, terms, etc.)</span></label>
                    <textarea rows={2} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500/40 outline-none resize-none" />
                  </div>
                </div>

                <div className="flex gap-3 pt-2">
                  <button type="button" onClick={() => setShowForm(false)}
                    className="flex-1 py-2.5 border border-slate-200 text-slate-500 text-sm font-semibold rounded-lg hover:bg-slate-50 transition-colors">
                    Cancel
                  </button>
                  <button type="submit"
                    className="flex-1 py-2.5 bg-slate-800 text-white text-sm font-semibold rounded-lg hover:bg-slate-800/90 transition-colors">
                    {editingDocId ? 'Update' : 'Create'} {tab === 'quote' ? 'Quote' : 'Invoice'}
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
